# Generated by Django 5.0.3 on 2026-05-20 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='opens_at',
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Успешный вход'), ('LOGIN_FAILED', 'Неверный пароль'), ('LOGIN_BLOCKED', 'Вход заблокирован (rate limit)'), ('LOGOUT', 'Выход'), ('TICKET_CREATED', 'Создан билет'), ('TICKET_UPDATED', 'Изменён билет'), ('TICKET_DELETED', 'Удалён билет'), ('ATTEMPT_STARTED', 'Начата попытка'), ('ATTEMPT_SUBMITTED', 'Сдана попытка'), ('USER_ROLE_CHANGED', 'Изменена роль пользователя'), ('OTP_VERIFIED', 'Пройдена двухфакторная аутентификация'), ('OTP_FAILED', 'Неверный OTP-код')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='api_auditlo_user_id_8f69e8_idx'), models.Index(fields=['action', 'timestamp'], name='api_auditlo_action_070bba_idx'), models.Index(fields=['ip_address', 'timestamp'], name='api_auditlo_ip_addr_f9c369_idx')],
            },
        ),
    ]
